# Generated by Django 4.2.1 on 2023-05-21 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentDesc', models.CharField(max_length=150)),
                ('checked', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('city', models.CharField(default='', max_length=64, verbose_name='city')),
                ('state', localflavor.us.models.USStateField(default='', max_length=2, verbose_name='state')),
                ('zip_code', localflavor.us.models.USZipCodeField(default='', max_length=10, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beltLevel', models.TextField(blank=True, null=True)),
                ('userDesc', models.TextField(blank=True, null=True)),
                ('martialArt', models.TextField(blank=True, null=True)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_first_name', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_last_name', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('postDesc', models.TextField(blank=True, null=True)),
                ('upload', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_of_post', to='api.comment')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_of_comment', to='api.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
