# Generated by Django 4.2.1 on 2023-05-26 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_username_alter_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='userId',
        ),
    ]
