# Generated by Django 4.2.1 on 2023-05-30 14:28

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_post_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(upload_to='uploads', validators=[api.validators.file_size]),
        ),
    ]
