# Generated by Django 4.2.1 on 2023-06-06 14:43

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(default='default', upload_to='pictures', validators=[api.validators.file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
