# Generated by Django 4.2.1 on 2023-06-07 16:31

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_picture_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(max_length=255, upload_to='uploads', validators=[api.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(max_length=255, upload_to='pictures', validators=[api.validators.file_size]),
        ),
    ]
