# Generated by Django 4.2.1 on 2023-06-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
